

INSERT INTO produit (nom, categorie, sous_categorie, emission_co2_par_unite, unite, source, identifiant_source, description)
SELECT * FROM (VALUES
   
    ('Pomme', 'Fruits et Légumes', 'Fruits', 0.35, 'kg', 'Base Carbone'::produit_source_enum, 'FR-PEP-001', 'Pomme toutes variétés (Golden, Gala...)'),
    ('Poire', 'Fruits et Légumes', 'Fruits', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-PEP-002', 'Poire (Conférence, Williams...)'),
    ('Coing', 'Fruits et Légumes', 'Fruits', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-PEP-003', 'Coing fruit frais'),
    ('Nèfle', 'Fruits et Légumes', 'Fruits', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'FR-PEP-004', 'Nèfle commune ou du Japon'),
    ('Nashi', 'Fruits et Légumes', 'Fruits', 0.80, 'kg', 'Base Carbone'::produit_source_enum, 'FR-PEP-005', 'Nashi (Pomme-poire)'),

  
    ('Abricot', 'Fruits et Légumes', 'Fruits', 0.90, 'kg', 'Base Carbone'::produit_source_enum, 'FR-NOY-001', 'Abricot frais'),
    ('Pêche', 'Fruits et Légumes', 'Fruits', 0.90, 'kg', 'Base Carbone'::produit_source_enum, 'FR-NOY-002', 'Pêche jaune ou blanche'),
    ('Nectarine', 'Fruits et Légumes', 'Fruits', 0.90, 'kg', 'Base Carbone'::produit_source_enum, 'FR-NOY-003', 'Nectarine ou Brugnon'),
    ('Cerise', 'Fruits et Légumes', 'Fruits', 0.80, 'kg', 'Base Carbone'::produit_source_enum, 'FR-NOY-004', 'Cerise (Burlat, Griotte...)'),
    ('Prune', 'Fruits et Légumes', 'Fruits', 0.70, 'kg', 'Base Carbone'::produit_source_enum, 'FR-NOY-005', 'Prune toutes variétés'),
    ('Mirabelle', 'Fruits et Légumes', 'Fruits', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'FR-NOY-006', 'Mirabelle de Lorraine'),
    ('Quetsche', 'Fruits et Légumes', 'Fruits', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'FR-NOY-007', 'Quetsche fraîche'),
    ('Reine-Claude', 'Fruits et Légumes', 'Fruits', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'FR-NOY-008', 'Reine-Claude'),
    ('Datte', 'Fruits et Légumes', 'Fruits', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'FR-NOY-009', 'Datte (Deglet Nour, Medjool)'),
    ('Olive', 'Fruits et Légumes', 'Légumes', 1.20, 'kg', 'Base Carbone'::produit_source_enum, 'FR-NOY-010', 'Olive de table verte ou noire'),


    ('Citron jaune', 'Fruits et Légumes', 'Fruits', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'FR-AGR-001', 'Citron jaune standard'),
    ('Citron vert', 'Fruits et Légumes', 'Fruits', 0.80, 'kg', 'Base Carbone'::produit_source_enum, 'FR-AGR-002', 'Lime / Citron vert'),
    ('Orange', 'Fruits et Légumes', 'Fruits', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-AGR-003', 'Orange à jus ou dessert'),
    ('Clémentine', 'Fruits et Légumes', 'Fruits', 0.40, 'kg', 'Base Carbone'::produit_source_enum, 'FR-AGR-004', 'Clémentine corse ou espagne'),
    ('Mandarine', 'Fruits et Légumes', 'Fruits', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-AGR-005', 'Mandarine'),
    ('Pamplemousse', 'Fruits et Légumes', 'Fruits', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'FR-AGR-006', 'Pamplemousse vrai'),
    ('Pomelo', 'Fruits et Légumes', 'Fruits', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-AGR-007', 'Pomelo rose ou jaune'),
    ('Kumquat', 'Fruits et Légumes', 'Fruits', 1.20, 'kg', 'Base Carbone'::produit_source_enum, 'FR-AGR-008', 'Kumquat entier'),
    ('Bergamote', 'Fruits et Légumes', 'Fruits', 0.70, 'kg', 'Base Carbone'::produit_source_enum, 'FR-AGR-009', 'Bergamote fraîche'),
    ('Yuzu', 'Fruits et Légumes', 'Fruits', 2.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-AGR-010', 'Yuzu frais import'),
    ('Cédrat', 'Fruits et Légumes', 'Fruits', 0.70, 'kg', 'Base Carbone'::produit_source_enum, 'FR-AGR-011', 'Cédrat'),
    ('Combava', 'Fruits et Légumes', 'Fruits', 1.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-AGR-012', 'Combava'),
    ('Calamondin', 'Fruits et Légumes', 'Fruits', 1.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-AGR-013', 'Calamondin / Oranger d''appartement'),
    ('Main de Bouddha', 'Fruits et Légumes', 'Fruits', 1.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-AGR-014', 'Main de Bouddha (zeste)'),


    ('Fraise', 'Fruits et Légumes', 'Fruits', 0.70, 'kg', 'Base Carbone'::produit_source_enum, 'FR-ROU-001', 'Fraise de saison'),
    ('Fraise des bois', 'Fruits et Légumes', 'Fruits', 0.80, 'kg', 'Base Carbone'::produit_source_enum, 'FR-ROU-002', 'Fraise des bois'),
    ('Framboise', 'Fruits et Légumes', 'Fruits', 1.10, 'kg', 'Base Carbone'::produit_source_enum, 'FR-ROU-003', 'Framboise'),
    ('Mûre', 'Fruits et Légumes', 'Fruits', 1.10, 'kg', 'Base Carbone'::produit_source_enum, 'FR-ROU-004', 'Mûre sauvage ou cultivée'),
    ('Myrtille', 'Fruits et Légumes', 'Fruits', 1.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-ROU-005', 'Myrtille / Bleuet'),
    ('Cassis', 'Fruits et Légumes', 'Fruits', 0.90, 'kg', 'Base Carbone'::produit_source_enum, 'FR-ROU-006', 'Baie de cassis'),
    ('Groseille', 'Fruits et Légumes', 'Fruits', 0.80, 'kg', 'Base Carbone'::produit_source_enum, 'FR-ROU-007', 'Groseille rouge'),
    ('Groseille à maquereau', 'Fruits et Légumes', 'Fruits', 0.80, 'kg', 'Base Carbone'::produit_source_enum, 'FR-ROU-008', 'Groseille à maquereau'),
    ('Airelle', 'Fruits et Légumes', 'Fruits', 1.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-ROU-009', 'Airelle rouge'),
    ('Cranberry', 'Fruits et Légumes', 'Fruits', 1.30, 'kg', 'Base Carbone'::produit_source_enum, 'FR-ROU-010', 'Cranberry / Canneberge'),
    ('Sureau', 'Fruits et Légumes', 'Fruits', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-ROU-011', 'Baies de sureau'),
    ('Goji', 'Fruits et Légumes', 'Fruits', 2.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-ROU-012', 'Baies de Goji séchées'),
    ('Aronia', 'Fruits et Légumes', 'Fruits', 0.80, 'kg', 'Base Carbone'::produit_source_enum, 'FR-ROU-013', 'Baie d''Aronia'),
    ('Argouse', 'Fruits et Légumes', 'Fruits', 0.80, 'kg', 'Base Carbone'::produit_source_enum, 'FR-ROU-014', 'Baie d''argousier'),

 
    ('Banane', 'Fruits et Légumes', 'Fruits', 0.80, 'kg', 'Base Carbone'::produit_source_enum, 'FR-TRO-001', 'Banane Cavendish'),
    ('Ananas', 'Fruits et Légumes', 'Fruits', 0.90, 'kg', 'Base Carbone'::produit_source_enum, 'FR-TRO-002', 'Ananas import'),
    ('Mangue', 'Fruits et Légumes', 'Fruits', 3.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-TRO-003', 'Mangue (avion possible)'),
    ('Avocat', 'Fruits et Légumes', 'Fruits', 1.30, 'kg', 'Base Carbone'::produit_source_enum, 'FR-TRO-004', 'Avocat Hass ou autre'),
    ('Kiwi', 'Fruits et Légumes', 'Fruits', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'FR-TRO-005', 'Kiwi vert ou jaune'),
    ('Fruit de la passion', 'Fruits et Légumes', 'Fruits', 4.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-TRO-006', 'Maracuja / Grenadille'),
    ('Papaye', 'Fruits et Légumes', 'Fruits', 2.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-TRO-007', 'Papaye'),
    ('Grenade', 'Fruits et Légumes', 'Fruits', 1.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-TRO-008', 'Grenade'),
    ('Litchi', 'Fruits et Légumes', 'Fruits', 1.20, 'kg', 'Base Carbone'::produit_source_enum, 'FR-TRO-009', 'Litchi frais'),
    ('Noix de coco', 'Fruits et Légumes', 'Fruits', 1.10, 'kg', 'Base Carbone'::produit_source_enum, 'FR-TRO-010', 'Noix de coco entière'),
    ('Figue', 'Fruits et Légumes', 'Fruits', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'FR-TRO-011', 'Figue fraîche'),
    ('Kaki', 'Fruits et Légumes', 'Fruits', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'FR-TRO-012', 'Kaki / Plaquemine'),


    ('Fruit du Dragon', 'Fruits et Légumes', 'Fruits', 3.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-001', 'Pitaya (rouge/blanc/jaune)'),
    ('Physalis', 'Fruits et Légumes', 'Fruits', 2.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-002', 'Amour en cage / Coqueret'),
    ('Carambole', 'Fruits et Légumes', 'Fruits', 2.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-003', 'Fruit étoile'),
    ('Ramboutan', 'Fruits et Légumes', 'Fruits', 2.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-004', 'Litchi chevelu'),
    ('Mangoustan', 'Fruits et Légumes', 'Fruits', 3.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-005', 'Mangoustan'),
    ('Durian', 'Fruits et Légumes', 'Fruits', 2.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-006', 'Durian'),
    ('Jacquier', 'Fruits et Légumes', 'Fruits', 1.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-007', 'Pomme de Jacque / Jackfruit'),
    ('Goyave', 'Fruits et Légumes', 'Fruits', 2.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-008', 'Goyave'),
    ('Feijoa', 'Fruits et Légumes', 'Fruits', 1.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-009', 'Goyavier du Brésil'),
    ('Tamarillo', 'Fruits et Légumes', 'Fruits', 1.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-010', 'Tomate en arbre'),
    ('Salak', 'Fruits et Légumes', 'Fruits', 2.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-011', 'Fruit serpent'),
    ('Longane', 'Fruits et Légumes', 'Fruits', 2.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-012', 'Œil du dragon'),
    ('Corossol', 'Fruits et Légumes', 'Fruits', 2.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-013', 'Graviola'),
    ('Pomme cannelle', 'Fruits et Légumes', 'Fruits', 2.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-014', 'Attier'),
    ('Sapotille', 'Fruits et Légumes', 'Fruits', 2.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-015', 'Sapotillier'),
    ('Sapote', 'Fruits et Légumes', 'Fruits', 2.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-016', 'Sapote noire ou blanche'),
    ('Kiwano', 'Fruits et Légumes', 'Fruits', 1.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-017', 'Concombre cornu'),
    ('Jaboticaba', 'Fruits et Légumes', 'Fruits', 1.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-018', 'Vigne brésilienne'),
    ('Ackée', 'Fruits et Légumes', 'Fruits', 1.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-019', 'Ackée'),
    ('Pepino', 'Fruits et Légumes', 'Fruits', 1.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-020', 'Poire-melon'),
    ('Ugli', 'Fruits et Légumes', 'Fruits', 1.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-021', 'Tangelo'),
    ('Baobab', 'Fruits et Légumes', 'Fruits', 1.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-EXO-022', 'Pain de singe (pulpe)'),


    ('Melon Charentais', 'Fruits et Légumes', 'Fruits', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-MEL-001', 'Melon type Cantaloup'),
    ('Melon Jaune', 'Fruits et Légumes', 'Fruits', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'FR-MEL-002', 'Melon Canari'),
    ('Melon Galia', 'Fruits et Légumes', 'Fruits', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'FR-MEL-003', 'Melon Galia'),
    ('Melon d''eau', 'Fruits et Légumes', 'Fruits', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-MEL-004', 'Honeydew'),
    ('Pastèque', 'Fruits et Légumes', 'Fruits', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-MEL-005', 'Pastèque rouge ou jaune'),


    ('Amande', 'Fruits et Légumes', 'Fruits à coque', 2.80, 'kg', 'Base Carbone'::produit_source_enum, 'FR-COC-001', 'Amande décortiquée'),
    ('Noisette', 'Fruits et Légumes', 'Fruits à coque', 2.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-COC-002', 'Noisette entière ou poudre'),
    ('Noix', 'Fruits et Légumes', 'Fruits à coque', 2.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-COC-003', 'Noix coque ou cerneaux'),
    ('Noix de Cajou', 'Fruits et Légumes', 'Fruits à coque', 3.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-COC-004', 'Noix de Cajou import'),
    ('Noix de Pécan', 'Fruits et Légumes', 'Fruits à coque', 3.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-COC-005', 'Pacane'),
    ('Pistache', 'Fruits et Légumes', 'Fruits à coque', 2.80, 'kg', 'Base Carbone'::produit_source_enum, 'FR-COC-006', 'Pistache grillée ou nature'),
    ('Noix de Macadamia', 'Fruits et Légumes', 'Fruits à coque', 3.80, 'kg', 'Base Carbone'::produit_source_enum, 'FR-COC-007', 'Macadamia'),
    ('Noix du Brésil', 'Fruits et Légumes', 'Fruits à coque', 3.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-COC-008', 'Noix d''Amazonie'),
    ('Châtaigne', 'Fruits et Légumes', 'Fruits', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'FR-COC-009', 'Châtaigne fraîche'),
    ('Marron', 'Fruits et Légumes', 'Fruits', 0.70, 'kg', 'Base Carbone'::produit_source_enum, 'FR-COC-010', 'Marron (grosse châtaigne)'),


    ('Tomate', 'Fruits et Légumes', 'Légumes', 0.80, 'kg', 'Base Carbone'::produit_source_enum, 'FR-LEG-001', 'Tomate ronde standard'),
    ('Aubergine', 'Fruits et Légumes', 'Légumes', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'FR-LEG-002', 'Aubergine'),
    ('Courgette', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-LEG-003', 'Courgette'),
    ('Concombre', 'Fruits et Légumes', 'Légumes', 0.70, 'kg', 'Base Carbone'::produit_source_enum, 'FR-LEG-004', 'Concombre'),
    ('Poivron', 'Fruits et Légumes', 'Légumes', 1.10, 'kg', 'Base Carbone'::produit_source_enum, 'FR-LEG-005', 'Poivron vert/rouge/jaune'),
    ('Piment', 'Épicerie salée', 'Épices', 2.00, 'kg', 'Base Carbone'::produit_source_enum, 'FR-LEG-006', 'Piment frais'),
    ('Citrouille', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-LEG-007', 'Citrouille'),
    ('Potiron', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-LEG-008', 'Potiron'),
    ('Butternut', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'FR-LEG-009', 'Doubeurre'),


    ('Pomme de terre', 'Fruits et Légumes', 'Légumes', 0.45, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-001', 'Pomme de terre chair ferme/tendre'),
    ('Carotte', 'Fruits et Légumes', 'Légumes', 0.30, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-002', 'Carotte'),
    ('Oignon', 'Fruits et Légumes', 'Légumes', 0.40, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-003', 'Oignon jaune/rouge/blanc'),
    ('Ail', 'Fruits et Légumes', 'Légumes', 0.40, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-004', 'Ail tête ou gousse'),
    ('Échalote', 'Fruits et Légumes', 'Légumes', 0.45, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-005', 'Échalote traditionnelle'),
    ('Poireau', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-006', 'Poireau entier'),
    ('Betterave', 'Fruits et Légumes', 'Légumes', 0.40, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-007', 'Betterave rouge crue'),
    ('Navet', 'Fruits et Légumes', 'Légumes', 0.40, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-008', 'Navet violet ou blanc'),
    ('Radis', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-009', 'Radis rose'),
    ('Radis noir', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-010', 'Radis noir hiver'),
    ('Céleri-rave', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-011', 'Céleri rave'),
    ('Panais', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-012', 'Panais'),
    ('Rutabaga', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-013', 'Chou-navet / Rutabaga'),
    ('Topinambour', 'Fruits et Légumes', 'Légumes', 0.45, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-014', 'Topinambour'),
    ('Salsifis', 'Fruits et Légumes', 'Légumes', 0.70, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-015', 'Salsifis ou Scorsonère'),
    ('Patate douce', 'Fruits et Légumes', 'Légumes', 0.45, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-016', 'Patate douce orange/blanche'),
    ('Manioc', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-017', 'Racine de Manioc / Cassava'),
    ('Igname', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-018', 'Igname / Yam'),
    ('Taro', 'Fruits et Légumes', 'Légumes', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-019', 'Racine de Taro'),
    ('Gingembre', 'Fruits et Légumes', 'Épices', 1.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-020', 'Racine de gingembre'),
    ('Curcuma', 'Fruits et Légumes', 'Épices', 1.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-021', 'Racine de curcuma'),
    ('Fenouil', 'Fruits et Légumes', 'Légumes', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-RAC-022', 'Bulbe de fenouil'),


    ('Laitue', 'Fruits et Légumes', 'Légumes', 0.70, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-FEU-001', 'Laitue (Batavia, Iceberg...)'),
    ('Mâche', 'Fruits et Légumes', 'Légumes', 1.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-FEU-002', 'Mâche nantaise'),
    ('Épinard', 'Fruits et Légumes', 'Légumes', 0.80, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-FEU-003', 'Épinard frais'),
    ('Blette', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-FEU-004', 'Blette / Carde'),
    ('Endive', 'Fruits et Légumes', 'Légumes', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-FEU-005', 'Endive / Chicon'),
    ('Roquette', 'Fruits et Légumes', 'Légumes', 1.00, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-FEU-006', 'Roquette'),
    ('Cresson', 'Fruits et Légumes', 'Légumes', 0.80, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-FEU-007', 'Cresson de fontaine'),
    ('Pissenlit', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-FEU-008', 'Feuilles de pissenlit'),
    ('Oseille', 'Fruits et Légumes', 'Légumes', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-FEU-009', 'Oseille'),
    ('Céleri-branche', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-FEU-010', 'Céleri branche'),

    ('Chou-fleur', 'Fruits et Légumes', 'Légumes', 0.60, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-CRU-001', 'Chou-fleur blanc'),
    ('Brocoli', 'Fruits et Légumes', 'Légumes', 0.70, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-CRU-002', 'Brocoli'),
    ('Chou vert', 'Fruits et Légumes', 'Légumes', 0.40, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-CRU-003', 'Chou frisé / Milan'),
    ('Chou rouge', 'Fruits et Légumes', 'Légumes', 0.40, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-CRU-004', 'Chou rouge'),
    ('Chou blanc', 'Fruits et Légumes', 'Légumes', 0.40, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-CRU-005', 'Chou cabus blanc'),
    ('Chou de Bruxelles', 'Fruits et Légumes', 'Légumes', 0.70, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-CRU-006', 'Choux de Bruxelles'),
    ('Chou Romanesco', 'Fruits et Légumes', 'Légumes', 0.70, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-CRU-007', 'Chou Romanesco'),
    ('Chou Kale', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-CRU-008', 'Chou Kale / Frisé non pommé'),
    ('Chou-rave', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-CRU-009', 'Chou-rave'),
    ('Chou Chinois', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-CRU-010', 'Pé-tsaï / Bok Choy'),


    ('Haricot vert', 'Fruits et Légumes', 'Légumes', 0.90, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-DIV-001', 'Haricot vert filet ou mange-tout'),
    ('Petit pois', 'Fruits et Légumes', 'Légumes', 0.80, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-DIV-002', 'Petit pois frais (écossé)'),
    ('Fève', 'Fruits et Légumes', 'Légumes', 0.80, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-DIV-003', 'Fève fraîche'),
    ('Asperge', 'Fruits et Légumes', 'Légumes', 2.30, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-DIV-004', 'Asperge verte ou blanche'),
    ('Artichaut', 'Fruits et Légumes', 'Légumes', 1.10, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-DIV-005', 'Artichaut globe ou violet'),
    ('Maïs', 'Fruits et Légumes', 'Légumes', 0.70, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-DIV-006', 'Épi de maïs doux'),
    ('Rhubarbe', 'Fruits et Légumes', 'Légumes', 0.40, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-DIV-007', 'Tige de rhubarbe'),
    ('Cardon', 'Fruits et Légumes', 'Légumes', 0.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-DIV-008', 'Cardon'),
    ('Pousses de bambou', 'Fruits et Légumes', 'Légumes', 1.20, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-DIV-009', 'Pousses de bambou'),
    ('Cœur de palmier', 'Fruits et Légumes', 'Légumes', 1.80, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-DIV-010', 'Cœur de palmier'),
    ('Gombo', 'Fruits et Légumes', 'Légumes', 1.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-DIV-011', 'Okra / Gombo'),


    ('Champignon de Paris', 'Fruits et Légumes', 'Légumes', 1.50, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-CHA-001', 'Champignon de Paris blanc/brun'),
    ('Cèpe', 'Fruits et Légumes', 'Légumes', 0.80, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-CHA-002', 'Bolet / Cèpe'),
    ('Girolle', 'Fruits et Légumes', 'Légumes', 0.80, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-CHA-003', 'Chanterelle / Girolle'),
    ('Pleurote', 'Fruits et Légumes', 'Légumes', 1.20, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-CHA-004', 'Pleurote'),
    ('Shiitake', 'Fruits et Légumes', 'Légumes', 1.30, 'kg', 'Base Carbone'::produit_source_enum, 'LEG-CHA-005', 'Lentin du chêne')

   
    ('Riz blanc', 'Épicerie salée', 'Féculents', 2.5, 'kg', 'Base Carbone'::produit_source_enum, 'AGRI-FEC-011', 'Riz blanc standard'),
    ('Riz complet', 'Épicerie salée', 'Féculents', 2.2, 'kg', 'Base Carbone'::produit_source_enum, 'AGRI-FEC-012', 'Riz complet brun'),
    ('Pâtes sèches', 'Épicerie salée', 'Féculents', 1.4, 'kg', 'Base Carbone'::produit_source_enum, 'AGRI-FEC-013', 'Pâtes alimentaires blé dur'),
    ('Lentilles vertes', 'Épicerie salée', 'Féculents', 0.9, 'kg', 'Base Carbone'::produit_source_enum, 'AGRI-FEC-014', 'Lentilles vertes sèches'),
    ('Lentilles corail', 'Épicerie salée', 'Féculents', 1.2, 'kg', 'Base Carbone'::produit_source_enum, 'AGRI-FEC-015', 'Lentilles corail sèches'),
    ('Pois cassés', 'Épicerie salée', 'Féculents', 0.8, 'kg', 'Base Carbone'::produit_source_enum, 'AGRI-FEC-016', 'Pois cassés secs'),
    ('Millet', 'Épicerie salée', 'Féculents', 1.0, 'kg', 'Base Carbone'::produit_source_enum, 'AGRI-FEC-017', 'Graines de millet décortiqué'),
    ('Orge perlé', 'Épicerie salée', 'Féculents', 1.1, 'kg', 'Base Carbone'::produit_source_enum, 'AGRI-FEC-018', 'Orge perlé sec'),
    ('Manioc', 'Fruits et Légumes', 'Féculents', 0.5, 'kg', 'Base Carbone'::produit_source_enum, 'AGRI-FEC-019', 'Racine de manioc'),
    ('Igname', 'Fruits et Légumes', 'Féculents', 0.5, 'kg', 'Base Carbone'::produit_source_enum, 'AGRI-FEC-020', 'Igname racine'),
    ('Farine de blé', 'Épicerie salée', 'Céréales', 1.1, 'kg', 'Base Carbone'::produit_source_enum, 'AGRI-FEC-021', 'Farine T55'),
    ('Polenta', 'Épicerie salée', 'Féculents', 1.0, 'kg', 'Base Carbone'::produit_source_enum, 'AGRI-FEC-022', 'Semoule de maïs'),

    
    ('Crème hydratante', 'Hygiène', 'Soins', 0.5, 'unité', 'Base Carbone'::produit_source_enum, 'HYG-015', 'Tube crème visage/corps (100ml)'),
    ('Baume à lèvres', 'Hygiène', 'Soins', 0.1, 'unité', 'Base Carbone'::produit_source_enum, 'HYG-016', 'Stick lèvres standard'),
    ('Mascara', 'Hygiène', 'Maquillage', 0.1, 'unité', 'Base Carbone'::produit_source_enum, 'HYG-017', 'Tube mascara'),
    ('Fond de teint', 'Hygiène', 'Maquillage', 0.3, 'unité', 'Base Carbone'::produit_source_enum, 'HYG-018', 'Flacon fond de teint'),
    ('Démaquillant', 'Hygiène', 'Soins', 1.5, 'litre', 'Base Carbone'::produit_source_enum, 'HYG-019', 'Eau micellaire ou lait'),
    ('Bain de bouche', 'Hygiène', 'Bucco-dentaire', 1.5, 'litre', 'Base Carbone'::produit_source_enum, 'HYG-020', 'Solution bain de bouche'),
    ('Fil dentaire', 'Hygiène', 'Bucco-dentaire', 0.05, 'unité', 'Base Carbone'::produit_source_enum, 'HYG-021', 'Boîte fil dentaire'),
    ('Coton-tige', 'Hygiène', 'Soins', 0.2, 'unité', 'Base Carbone'::produit_source_enum, 'HYG-022', 'Boîte de cotons-tiges (papier)'),
    ('Crème solaire', 'Hygiène', 'Soins', 0.8, 'unité', 'Base Carbone'::produit_source_enum, 'HYG-023', 'Tube crème solaire 200ml'),
    ('Mousse à raser', 'Hygiène', 'Rasage', 0.5, 'unité', 'Base Carbone'::produit_source_enum, 'HYG-024', 'Bombe mousse à raser'),
    ('Lotion tonique', 'Hygiène', 'Soins', 1.5, 'litre', 'Base Carbone'::produit_source_enum, 'HYG-025', 'Lotion visage'),
    ('Gommage corps', 'Hygiène', 'Soins', 0.6, 'unité', 'Base Carbone'::produit_source_enum, 'HYG-026', 'Pot gommage exfoliant'),


    ('Vinaigre blanc', 'Ménage', 'Désinfectant', 0.4, 'litre', 'Base Carbone'::produit_source_enum, 'MEN-013', 'Vinaigre ménager 14°'),
    ('Bicarbonate de soude', 'Ménage', 'Surface', 0.8, 'kg', 'Base Carbone'::produit_source_enum, 'MEN-014', 'Poudre bicarbonate'),
    ('Savon noir', 'Ménage', 'Surface', 1.0, 'litre', 'Base Carbone'::produit_source_enum, 'MEN-015', 'Savon noir liquide'),
    ('Désodorisant', 'Ménage', 'Air', 3.0, 'unité', 'Base Carbone'::produit_source_enum, 'MEN-016', 'Spray aérosol'),
    ('Insecticide', 'Ménage', 'Nuisibles', 4.0, 'unité', 'Base Carbone'::produit_source_enum, 'MEN-017', 'Spray insecticide'),
    ('Bloc WC', 'Ménage', 'Sanitaires', 0.5, 'unité', 'Base Carbone'::produit_source_enum, 'MEN-018', 'Bloc cuvette WC'),
    ('Lingettes nettoyantes', 'Ménage', 'Surface', 1.5, 'unité', 'Base Carbone'::produit_source_enum, 'MEN-019', 'Paquet lingettes jetables'),
    ('Déboucheur', 'Ménage', 'Sanitaires', 3.5, 'litre', 'Base Carbone'::produit_source_enum, 'MEN-020', 'Gel déboucheur canalisations'),
    ('Cire pour meubles', 'Ménage', 'Surface', 2.0, 'litre', 'Base Carbone'::produit_source_enum, 'MEN-021', 'Cire liquide bois'),
    ('Sel lave-vaisselle', 'Ménage', 'Vaisselle', 0.5, 'kg', 'Base Carbone'::produit_source_enum, 'MEN-022', 'Sel régénérant')

) AS v(nom, categorie, sous_categorie, emission_co2_par_unite, unite, source, identifiant_source, description)
WHERE NOT EXISTS (
    SELECT 1 FROM produit p WHERE p.nom = v.nom
);